### ISSUE TITLE
adv7282m mipi interface

### ISSUE THREAD

**Issue by Maobuff** [6by9/CSI2_device_config#1]
Hello, Im interesting in design my custom board for converting analog video to digital, and Im curious how to connect adv7282m to rpi (in my case 2b or cm3). After looking on pinout of csi connector of rpi I found that there are some CAM_IO0 and CAM_IO1 pins, do i have to connect them to GPIO0...2 of an adv7282, also what about ~INTRQ, ~RESET pins. 
Can you provide schematic how to connect them together?
Can I specify input channel and mode (INSEL[4:0] Bits)?

**Comment by 6by9** [comment]
Totally the wrong place to ask. Please use the Raspberry Pi forums (either Camera Board or Interfacing suforums).
But no, you don't need any control signals other than SCL and SDA of the I2C.

See the driver for the ADV7180 family of chips for details of selecting inputs - https://github.com/raspberrypi/linux/blob/rpi-4.19.y/drivers/media/i2c/adv7180.c
Yes it's possible via the s_routing function.
